version: "3.8"
services:
  hovdusa-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hovdusa
    restart: unless-stopped
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
